export const colors = {
    primary: '#1a1a1a',
    secondary: '#2b2b2b',
    fontColor: '#f0f0f0',
    lightBlueColor: 'dodgerblue',
    mediumBlueColor: '#1E90FF',
    darkBlueColor: '#187bcd',
    inactiveColor: 'grey',
    greenColor: 'green',
    redAlertColor: 'red',
    lightRed: '#af3939',
    darkcyan: 'darkcyan',
    lightcyan: 'lightcyan',
    discordBackground: '#7289da',
}